Fix a race condition
Happens when many threads execute REST client call at the same.

Symptom:

Occasional 
IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
from WebTarget.request

Reason for the exception:
* The injectionManager is set earlier than it's used, it's stored to a shared volatile variable and later picked up
* If some thread sets the shared volatile variable to another injectionManager, the original thread would use another threads injectionManager
* In case the second thread doesn't bind the ClassAnalyzer class in time before the first thread uses it, the first thread won't have ClassAnalyzer bean available and throws exception